import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import { Leaderboard } from "../components";
import styles from "../styles/Home.module.scss";

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Image
          src="/images/rps-logo.png"
          height={226}
          width={350}
          alt="rps-logo"
          objectFit="contain"
        />
        <Leaderboard />
        <div className={styles.play__buttons}>
          <button type="button">Play as guest</button>
          <button type="button">Sign In/Sign Up</button>
          <button type="button">How to play</button>
        </div>
      </main>
    </div>
  );
};

export default Home;
